language: node_js
node_js:
  - "8"
script:
  - npm test
  - npm run coverage
before_install:
    npm install --save react@16 react-dom@16
after_script:
    npm install coveralls && nyc report --reporter=text-lcov | coveralls